provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  nodeinfo:
    image: functions/nodeinfo:latest
    annotations:
      topic: cron-function
      schedule: "* * * * *"
  nodeinfo:
    image: functions/nodeinfo:latest
    annotations:
      topic: cron-function
      schedule: "* * * * *"
	  # async call
      async: true	
